name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - os-image: windows-2019
          os-name: windows

    runs-on: ${{ matrix.config.os-image }}

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10'

    - run: npm install
    - run: npm run package # creates pkg/avatar-animator-<os> folder

    - name: Store package as artifact
      uses: actions/upload-artifact@v1
      with:
        name: pkg
        path: pkg

  deploy:
    runs-on: ubuntu-latest

    needs: [build]

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download packages from artifact storage
      uses: actions/download-artifact@v1
      with:
        name: pkg
        path: pkg

    - run: cd pkg && zip -r avatar-animator-windows.zip avatar-animator-win32-x64

    - name: Create draft release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true

    - name: Upload release asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pkg/avatar-animator-windows.zip
        asset_name: avatar-animator-windows.zip
        asset_content_type: application/zip
      